/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "STM32F446xx.h"
#include "RCC_interface.h"

#include "SCB_interface.h"
#include "NVIC_interface.h"
#include "DMA_interface.h"

int x = 0;

void LED(void)
{
	x = 1;
}
int main(void)
{

	uint32_t SrcArr[16] = {0};
	uint32_t DestArr[16] = {0};

	RCC_u8PeripheralClkEnable(DMA2_Per, RCC_AHB1_CLK);

	DMA_Cnfg_T DMA_Test;

	DMA_Test.DMA_Type = DMA_2;
	DMA_Test.ChannelNum = CHANNEL0;
	DMA_Test.MemIncMode = INCREMENT;
	DMA_Test.PerIncMode = INCREMENT;
	DMA_Test.MemIncSize = WORD;
	DMA_Test.PerIncSize = WORD;

	DMA_Test.PriorityLevel = LOW;
	DMA_Test.SrcDestMode = MEM_TO_MEM;
	DMA_Test.StreamNum = STREAM5;
	DMA_Test.TransferMode = DIRECT_MODE;
	DMA_Test.InterruptType = FULL_TRANS;

	DMA_Test.CallBackFunc = &LED;

	DMA_Test.InterruptType = FULL_TRANS;

	DMA_u8Init(&DMA_Test);

	NVIC_voidEnableIRQ(DMA2_Stream5_IRQ);

	for(int i = 0 ; i < 16 ; i++)
	{
		SrcArr[i] = i;
	}
	DMA_u8StartTransfer(&DMA_Test, SrcArr, DestArr, 16);

	while(1)
    {

    }
}
