/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "RCC_interface.h"
#include "GPIO_interface.h"
#include "SPI_interface.h"

int main(void)
{
	RCC_APB2EnableClock(APB2_IOPA);
	RCC_APB2EnableClock(APB2_SPI1);

	GPIO_PinConfig_T SPI_MOSIpin=
	{
		.Port=PORTA,
		.InputOutConfig=AF_PUSHPULL,
		.Mode=INPUT,
		.PinNum=PIN7,
	};
	GPIO_PinConfig_T SPI_MISOpin=
	{
		.Port=PORTA,
		.InputOutConfig=AF_PUSHPULL,
		.Mode = OUTPUT_10MHZ,
		.PinNum=PIN6,
	};
	GPIO_PinConfig_T SPI_SCKpin=
	{
		.Port=PORTA,
		.InputOutConfig=AF_PUSHPULL,
		.Mode=INPUT,
		.PinNum=PIN5,
	};
	GPIO_PinConfig_T SPI_NSSpin=
		{
			.Port=PORTA,
			.InputOutConfig=AF_PUSHPULL,
			.Mode=INPUT,
			.PinNum=PIN4,
		};
	GPIO_u8PinInit(&SPI_MOSIpin);
	GPIO_u8PinInit(&SPI_MISOpin);
	GPIO_u8PinInit(&SPI_SCKpin);
	GPIO_u8PinInit(&SPI_NSSpin);
	SPI_Config_ty SPI_setting=
	{
		.ClockSpeed=SPI_FclkDiv_256,
		.DataFrameLenght=SPI_8_BIT_DATA_FRAME,
		.InterruptsStates.RxBufferNotEmptyInter=SPI_INTER_ENABLE,
		.LinesDirections=SPI_2LineUnidirectional,
		.SpiNumber=SPI_1,
		.SPIperiphState=SPI_ENABLE,
		.SpiState=SPI_SlAVE,
		.SLaveSlection=SPI_SlaveSlection_SW,
	};
	SPI_u8Init(&SPI_setting);
	//SPI_u8SlaveSWslection(SPI_1);
	uint16_t chrecter;
	SPI_u8ReciveData_pulling(SPI_1,&chrecter);
	while(SPI_u8AreYouBusy(SPI_1)==1);
	uint8_t arry[11]={0};
	SPI_u8ReciveData_IT(SPI_1, 11,&arry[0]);
	for(;;);
}
