#ifndef RCC_PRV_H_
#define RCC_PRV_H_

#define CLKYYPE_FLAG   	 	(ClkType + 1)
#define CLKYYPE_TIMEOUT 	50000U
#define ONE_BIT_MASKING 	1U
#define TWO_BITS_MASKING 	0b11U
#define FOUR_BITS_MASKING 	0b1111U
/*RCC_CR bits*/
typedef enum
{
	
	RCC_CR_HSION     =0,
	RCC_CR_HSIRDY    =1,
	RCC_CR_HSITRIM_0 =3,
	RCC_CR_HSITRIM_1 =4,
	RCC_CR_HSITRIM_2 =5,
	RCC_CR_HSITRIM_3 =6,
	RCC_CR_HSITRIM_4 =7,
	RCC_CR_HSICAL_0  =8,
	RCC_CR_HSICAL_1  =9,
	RCC_CR_HSICAL_2  =10,
	RCC_CR_HSICAL_3  =11,
	RCC_CR_HSICAL_4  =12,
	RCC_CR_HSICAL_5  =13,
	RCC_CR_HSICAL_6  =14,
	RCC_CR_HSICAL_7  =15,
	RCC_CR_HSEON  	 =16,
	RCC_CR_HSERDY    =17,
	RCC_CR_HSEBYP    =18,
	RCC_CR_CSSON  	 =19,
	RCC_CR_PLLON     =24,
	RCC_CR_PLLRDY	 =25,
}RCC_CR_bits_t;
/*RCC_CFGR bits*/
typedef enum
{
	RCC_CFGR_SW_0	  =0,
	RCC_CFGR_SW_1	  =1,
	RCC_CFGR_SWS_0	  =2,
	RCC_CFGR_SWS_1	  =3,
	RCC_CFGR_HPRE_0	  =4,
	RCC_CFGR_HPRE_1	  =5,
	RCC_CFGR_HPRE_2	  =6,
	RCC_CFGR_HPRE_3	  =7,
	RCC_CFGR_PPRE1_0  =8,
	RCC_CFGR_PPRE1_1  =9,
	RCC_CFGR_PPRE1_2  =10,
	RCC_CFGR_PPRE2_0  =11,
	RCC_CFGR_PPRE2_1  =12,
	RCC_CFGR_PPRE2_2  =13,
	RCC_CFGR_ADCPRE_0 =14,
	RCC_CFGR_ADCPRE_1 =15,
	RCC_CFGR_PLLSRC   =16,
	RCC_CFGR_PLLXTPRE =17,
	RCC_CFGR_PLLMUL_0 =18,
	RCC_CFGR_PLLMUL_1 =19,
	RCC_CFGR_PLLMUL_2 =20,
	RCC_CFGR_PLLMUL_3 =21,
	RCC_CFGR_USBPRE	  =22,
	RCC_CFGR_MCO_0	  =24,
	RCC_CFGR_MCO_1	  =25,
	RCC_CFGR_MCO_2	  =26,
}RCC_CFGR_bits_t;


#endif