/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "ERROR_STATE.h"

#include "RCC_interface.h"
#include "USART_interface.h"
#include "GPIO_interface.h"

#include "USR_interface.h"
#include "USR_sctipts.h"

int main(void)
{

	/********************	Local variables initialization	********************/
	uint8_t Local_u8EnteredPass[USR_PASS_LENGTH],
	Local_u8PassFlag,
	Local_u8Trials = 0;

	uint8_t Local_u8NewDate[USR_DATE_LENGTH],
			Local_u8NewTime[USR_TIME_LENGTH];

	USR_Choice_T Local_u8Choice;

	/*************************	Clock Settings	*****************************/
	RCC_u8SetClksts(CLK_HSI, STATE_ON);
	RCC_SetSysClk(HSI);

	RCC_voidAPB1EnablePerapheralClock(APB1_USART2);
	RCC_voidAHB1EnablePerapheralClock(AHB1_GPIOA);


	/*********************	GPIO Pins configurations ***********************/
	GPIO_PinConfig_T USARTPinRX =
	{
			.AltFunc = AF7,
			.Mode = ALTER_FUNC,
			.PinNum = PIN2,
			.Port = PORTA,
			.PullType = PUSH_PULL,
			.Speed = SPEED_LOW
	};

	GPIO_PinConfig_T USARTPinTX =
	{
			.AltFunc = AF7,
			.Mode = ALTER_FUNC,
			.PinNum = PIN3,
			.Port = PORTA,
			.PullType = PUSH_PULL,
			.Speed = SPEED_LOW
	};


	/*********************	USART configuration	*************************/
	USARTconfig_t USR_USART_Cnfg =
	{
			.DMAresevier = DMAR_DISABLE,
			.DMAtransmitter = DMAT_DISABLE,
			.ErrorTnterrupt = INHIBITED,
			.OverSampling = BY_16,
			.ParityControl = PARITY_CONTROL_DISABLE,
			.RXNEinterrupt = RXNE_INTERRUPT_DISABLE,
			.Receiver = RECEIVER_ENABLE,
			.StopBit_t = ONE_BIT,
			.TXEinterrupt = TXE_INTERRUPT_DISABLE,
			.TransmetCompleteInterrupt = TRANSMITTER_COMPLETE_INTERRUPT_DISABLE,
			.Transmitter = TRANSMITTER_ENABLE,
			.USARTindex = USART_2,
			.WordLength = DATA_8_BITS,
			.ParitySelection = PARITY_SELECTION_EVEN
	};


	/***********************	MCAL Initialization ***********************/
	MUSART_u8SetConfiguration(&USR_USART_Cnfg);
	GPIO_u8PinInit(&USARTPinRX);
	GPIO_u8PinInit(&USARTPinTX);


	/*******************	User Interface Program	***********************/
	USR_voidSendWelcome(USR_USART_Cnfg.USARTindex);

	do
	{

		if(Local_u8Trials != 0)
		{
			USR_voidSendWrongPass(USR_USART_Cnfg.USARTindex);
		}

		Local_u8PassFlag = USR_u8ReceivePass(USR_USART_Cnfg.USARTindex);
		Local_u8Trials++;
	}
	while((Local_u8PassFlag == PASS_NOT_CORRECT) && (Local_u8Trials < USR_MAX_TRIALS));

	if(Local_u8PassFlag == PASS_NOT_CORRECT)
	{
		USR_voidSendLoginFailed(USR_USART_Cnfg.USARTindex);
	}

	else
	{
		USR_voidSendDashBoard(USR_USART_Cnfg.USARTindex);
		MUSART_u8ReceiveCharSynch(USR_USART_Cnfg.USARTindex, &Local_u8Choice);
	}


	switch(Local_u8Choice)
	{
	case CHOICE_DISPLAY :

		/*Call RTC to get time*/
		break;

	case CHOICE_SET_TIME :

		USR_voidReceiveTimeDate(USR_USART_Cnfg.USARTindex ,Local_u8NewDate ,Local_u8NewTime);
		break;

	case CHOICE_SET_ALRM :

		break;

	default :
		break;
	}


	while(1)
	{

	}
}

