/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "ERROR_STATE.h"
/******************************************************************************/
/************************ MCAL Layer ******************************************/
/******************************************************************************/
#include "RCC_interface.h"
#include "USART_interface.h"
#include "GPIO_interface.h"
/******************************************************************************/
/************************ HAL Layer *******************************************/
/******************************************************************************/
#include "RTC_interface.h"
/******************************************************************************/
/******************************************************************************/
/******************************************************************************/
//#include "USR_interface.h"
//#include "USR_sctipts.h"

#include "APP1_interface.h"
#include "APP_2_interface.h"
#include "APP3_interface.h"

extern uint8_t Globla_Alrams_Flags_state;
int main(void)
{
	/*************************	Clock Settings	*****************************/
	RCC_u8SetClksts(CLK_HSI, STATE_ON);
	RCC_SetSysClk(HSI);

	RCC_voidAPB1EnablePerapheralClock(APB1_USART2);
	RCC_voidAHB1EnablePerapheralClock(AHB1_GPIOA);

	RCC_voidAPB2EnablePerapheralClock(APB2_SPI11);
	RCC_voidAHB1EnablePerapheralClock(AHB1_GPIOB);
	RCC_voidAPB1EnablePerapheralClock(APB1_I2C1);
	/********************************************************************************************************************************************/
	/**************************************************** RTC initialization ********************************************************************/
	/********************************************************************************************************************************************/
	HRTC_u8Init();

	/* APP1 Initialization*/
	APP1_voidInit();

	/********************************************************************************************************************************************/
	/**************************************************** APP3 initialization *******************************************************************/
	/********************************************************************************************************************************************/
	APP3_voidinit();


	/********************	Local variables initialization	********************/
	uint8_t Local_u8Pulstemp ;
	APP1_AlarmSelect Local_u8AlrmNumber;

	APP1_Alarm_T Local_NewDateTime=
	{
			.Date = "\0",
			.Name = "NewDate",
			.Time = "\0"
	};

	APP1_Alarm_T Local_Alarms[APP1_MAX_ALRMS]= {"\0"};

	APP1_Choice Local_u8Choice;


	RTC_time_t SetTime,GetTime;
	RTC_date_t SetDate,GetDate;


	HRTC_voidSetCurrentTimeDate(&SetTime, &SetDate);


	HRTC_voidGetCurrentTimeDate(&GetTime, &GetDate);




	/* Login System */
	if((APP1_u8LoginSystem())== PASS_NOT_CORRECT)
	{
		/*************************** Turn On Red Led *******************************************/
		APP3_voidTurnOnRedLed();

		APP1_voidFaliedLogin();
	}

	/* Logged in successfully*/
	else
	{
		/*************************** Turn On Green Led *****************************************/
		APP3_voidTurnOnGreenLed();

		/* Set Time for the first time */
		APP1_voidReceiveTimeDate(&Local_NewDateTime);

		/* Set new time & date*/
		APP2_voidSetTime(&Local_NewDateTime);

		/* Date and time is updated */
		APP1_voidTimeIsSet();

		/* initialize APP2*/
		APP2_voidInit();


		do
		{
			if (Globla_Alrams_Flags_state!=0)
			{
				/********************************************************
				 * alarm EXTI and notification
				 */
				if (((Globla_Alrams_Flags_state>>APP2_ALARM_1)&1)==1)
				{
					/*send the name of alarm 1 */
					APP3_voidAlarmCompareMatch((uint8_t *)&Local_Alarms[ALRM1-1].Name);

					/*clear bit*/
					Globla_Alrams_Flags_state &=~(1<<APP2_ALARM_1);
				}
				if (((Globla_Alrams_Flags_state>>APP2_ALARM_2)&1)==1)
				{
					/*send the name of alarm 2 */
					APP3_voidAlarmCompareMatch((uint8_t *)&Local_Alarms[ALRM2-1].Name);

					/*clear bit*/
					Globla_Alrams_Flags_state &=~(1<<APP2_ALARM_2);
				}
				if (((Globla_Alrams_Flags_state>>APP2_ALARM_3)&1)==1)
				{
					/*send the name of alarm 3 */
					APP3_voidAlarmCompareMatch((uint8_t *)&Local_Alarms[ALRM1-3].Name);

					/*clear bit*/
					Globla_Alrams_Flags_state &=~(1<<APP2_ALARM_3);
				}
				if (((Globla_Alrams_Flags_state>>APP2_ALARM_4)&1)==1)
				{
					/*send the name of alarm 4 */
					APP3_voidAlarmCompareMatch((uint8_t *)&Local_Alarms[ALRM4-1].Name);

					/*clear bit*/
					Globla_Alrams_Flags_state &=~(1<<APP2_ALARM_4);
				}
				if (((Globla_Alrams_Flags_state>>APP2_ALARM_5)&1)==1)
				{
					/*send the name of alarm 5 */
					APP3_voidAlarmCompareMatch((uint8_t *)&Local_Alarms[ALRM5-1].Name);

					/*clear bit*/
					Globla_Alrams_Flags_state &=~(1<<APP2_ALARM_5);
				}
			}

			/* Display dash-board*/
			Local_u8Choice = APP1_u8DisplayDashBoard();

			switch(Local_u8Choice)
			{
			case CHOICE_DISPLAY :

				APP2_voidReadDateTime();
				HRTC_voidGetCurrentTimeDate(&GetTime, &GetDate);

				/**** Display On LCD ****/
				APP3_voidDisplayTime(&GetTime);

				for (uint32_t Local_u8Counter =0 ; Local_u8Counter<=10000;Local_u8Counter++)
				{
					Local_u8Pulstemp=Local_u8Counter;
				}

				APP3_voidDisplayDate(&GetDate);

				break;

			case CHOICE_SET_TIME :

				/* Get new time & date */
				APP1_voidReceiveTimeDate(&Local_NewDateTime);

				/* Set new time & date*/
				APP2_voidSetTime(&Local_NewDateTime);

				/* Date and time is update d*/
				APP1_voidTimeIsSet();

				break;

			case CHOICE_SET_ALRM :

				/*Set Alarm*/
				Local_u8AlrmNumber = APP1_u8SetAlarmCnfg(Local_Alarms);

				APP2_voidSetAlarm(&Local_Alarms[Local_u8AlrmNumber-1], Local_u8AlrmNumber-1);

				/* New alarm is set */
				APP1_voidAlarmIsSet();

				break;

			case CHOICE_EXIT :

				/* Exit the system */
				APP1_voidExit();
				break;

			default :
				/* Invalid Choice */
				APP1_voidInvalidChoice();

				break;
			}
		}
		while(Local_u8Choice != CHOICE_EXIT);
	}

	while(1)
	{

	}
}

